version: '2'

networks:
  development:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.201.0.0/16
  gitlab:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.202.0.0/16
  logging:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.203.0.0/16
  metrics:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.204.0.0/16

services:

  cadvisor:
    extends:
      file: docker-compose-common.yml
      service: cadvisor
    container_name: knecht-cadvisor1

  #consul:
  #  extends:
  #    file: docker-compose-common.yml
  #    service: consul
  #  container_name: knecht-consul1

###
# dev build environment
###
  zookeeper:
    extends:
      file: docker-compose-dev-common.yml
      service: zookeeper
    container_name: knecht-zookeeper1

  master:
    extends:
      file: docker-compose-dev-common.yml
      service: master
    container_name: knecht-mesos-master1
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper

  slave:
    extends:
      file: docker-compose-dev-common.yml
      service: slave
    container_name: knecht-mesos-slave1
    depends_on:
      - zookeeper
      - master
    links:
      - zookeeper:zookeeper
      - master:master

  marathon:
    extends:
      file: docker-compose-dev-common.yml
      service: marathon
    container_name: knecht-marathon1
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper

  marathonlb:
    extends:
      file: docker-compose-dev-common.yml
      service: marathonlb
    container_name: knecht-marathon-lb1
    depends_on:
      - zookeeper
      - marathon
      - master
    links:
      - zookeeper:zookeeper
      - marathon:marathon
      - master:"master.mesos"

  jenkins:
    extends:
      file: docker-compose-dev-common.yml
      service: jenkins
    container_name: knecht-jenkins1
    depends_on:
      - marathon
    links:
      - marathon:marathon
###
# dev build environment (end)
###


###
# docker registry
###
  registry:
    extends:
      file: docker-compose-registry-common.yml
      service: registry
    container_name: knecht-registry1

  registryui:
    extends:
      file: docker-compose-registry-common.yml
      service: registryui
    container_name: knecht-registry-ui1
    depends_on:
      - registry
    links:
      - registry:registry
###
# docker registry (end)
###


###
# gitlab
###
  gitlabredis:
    extends:
      file: docker-compose-gitlab-common.yml
      service: gitlabredis
    container_name: knecht-gitlab-redis1

  gitlabdb:
    extends:
      file: docker-compose-gitlab-common.yml
      service: gitlabdb
    container_name: knecht-gitlab-postgres1

  gitlab:
    extends:
      file: docker-compose-gitlab-common.yml
      service: gitlab
    container_name: knecht-gitlab1
    depends_on:
      - gitlabredis
      - gitlabdb
    links:
      - gitlabredis:redis
      - gitlabdb:postgresql
###
# gitlab (end)
###


###
# ELK stack + logspout
###
  elasticsearch:
    extends:
      file: docker-compose-elk-common.yml
      service: elasticsearch
    build: dockerfiles/elasticsearch
    container_name: knecht-elasticsearch1

  logstash:
    extends:
      file: docker-compose-elk-common.yml
      service: logstash
    build: dockerfiles/logstash
    container_name: knecht-logstash1
    links:
      - elasticsearch:elasticsearch

  kibana:
    extends:
      file: docker-compose-elk-common.yml
      service: kibana
    build: dockerfiles/kibana
    container_name: knecht-kibana1

  logspout:
    extends:
      file: docker-compose-elk-common.yml
      service: logspout
    container_name: knecht-logspout1
    links:
      - logstash:logstash
###
# ELK stack + logspout (end)
###


###
# TICK stack + grafana
###
  influxdb:
    extends:
      file: docker-compose-tick-common.yml
      service: influxdb
    build: dockerfiles/influxdb
    container_name: knecht-influxdb1

  grafana:
    extends:
      file: docker-compose-tick-common.yml
      service: grafana
    build: dockerfiles/grafana
    container_name: knecht-grafana1
    depends_on:
      - influxdb
      - elasticsearch
    links:
      - influxdb:influxdb
      - elasticsearch:elasticsearch

  telegraf:
    extends:
      file: docker-compose-tick-common.yml
      service: telegraf
    build: dockerfiles/telegraf
    container_name: knecht-telegraf1
    depends_on:
      - influxdb
      - elasticsearch
      - zookeeper
      - marathon
      - marathonlb
      - master
      - slave
    links:
      - influxdb:influxdb
      - elasticsearch:elasticsearch
      - zookeeper:zookeeper
      - marathon:marathon
      - marathonlb:marathonlb
      - master:master
      - slave:slave
###
# TICK stack + grafana (end)
###