version: '2'

networks:
  logging:
    driver: bridge

services:

  cadvisor:
    extends:
      file: docker-compose-common.yml
      service: cadvisor
    container_name: knecht-cadvisor1


###
# dev build environment
###
  zookeeper:
    extends:
      file: docker-compose-dev-common.yml
      service: zookeeper
    container_name: knecht-zookeeper1


  master:
    extends:
      file: docker-compose-dev-common.yml
      service: master
    container_name: knecht-mesos-master1
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper


  slave:
    extends:
      file: docker-compose-dev-common.yml
      service: slave
    container_name: knecht-mesos-slave1
    depends_on:
      - zookeeper
      - master
    links:
      - zookeeper:zookeeper
      - master:master


  marathon:
    extends:
      file: docker-compose-dev-common.yml
      service: marathon
    container_name: knecht-marathon1
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper


  jenkins:
    extends:
      file: docker-compose-dev-common.yml
      service: jenkins
    container_name: knecht-jenkins1
    depends_on:
      - marathon
    links:
      - marathon:marathon


  registry:
    extends:
      file: docker-compose-dev-common.yml
      service: registry
    container_name: knecht-registry1

###
# dev build environment (end)
###

###
# ELK stack + logspout
###
  elasticsearch:
    extends:
      file: docker-compose-elk-common.yml
      service: elasticsearch
    build: dockerfiles/elasticsearch
    container_name: knecht-elasticsearch1


  logstash:
    extends:
      file: docker-compose-elk-common.yml
      service: logstash
    build: dockerfiles/logstash
    container_name: knecht-logstash1
    links:
      - elasticsearch:elasticsearch


  kibana:
    extends:
      file: docker-compose-elk-common.yml
      service: kibana
    build: dockerfiles/kibana
    container_name: knecht-kibana1


  logspout:
    extends:
      file: docker-compose-elk-common.yml
      service: logspout
    container_name: knecht-logspout1
    links:
      - logstash:logstash
###
# ELK stack + logspout (end)
###
