# Setup front-end
frontend:
  image: konradkleine/docker-registry-frontend:v2
  #build: ../
  links:
    - registry:registry
  ports:
    # Publish the frontend's port 443 on the IP 0.0.0.0 on port 8443
    - "0.0.0.0:8443:443"
  volumes:
    - ./frontend/certs/frontend.crt:/etc/apache2/server.crt:ro
    - ./frontend/certs/frontend.key:/etc/apache2/server.key:ro
  environment:
    # The front-end is SSL protected
    - ENV_USE_SSL=yes
    - ENV_DOCKER_REGISTRY_HOST=registry
    - ENV_DOCKER_REGISTRY_PORT=5000
    # The registry is SSL protected as well
    - ENV_DOCKER_REGISTRY_USE_SSL=1

# Setup registry
registry:
  image: registry:2.2.0
  volumes:
    # Mount the config directory
    - ./registry/config:/etc/docker/registry:ro
    # Make the registry storage persistent (see ./config/config.yml for the path)
    - ./registry/storage:/var/lib/registry:rw
    # Mount our own certificate and key
    - ./registry/certs:/certs:ro
  ports:
    # Publish registry's port 5000 on the IP 0.0.0.0 on port 5000
    - "0.0.0.0:5000:5000"
